<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root84
 * Date: Thu, 20 Jun 2024 12:16:55 +0300
 */

$conf['title'] = 'Journal of Technical Literature';
$conf['start'] = 'catalog';
$conf['tagline'] = 'FAST SEARCH LIBRARY v1.4f+ [2023-01-18]';
$conf['license'] = '';
$conf['recent_days'] = 8;
$conf['breadcrumbs'] = 34;
$conf['youarehere'] = 1;
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['jpg_quality'] = 100;
$conf['readdircache'] = 4;
$conf['plugin']['odt']['orientation'] = 'landscape';
