# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 13 Sep 2022 12:19:32 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

root84:$2y$10$yVtnnHQLRwEhrFtc5LEYBOVA3kLfUiPp/l2/4lacIfgy3PS229zE2:root:email@email.com:admin,user
